name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: |
        docker build ./api -t barminz/argo_app_api:${{ github.head_ref }}.${{ github.sha }}
        docker build ./client -t barminz/argo_app_client:${{ github.head_ref }}.${{ github.sha }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push current version
      run: |
        docker push barminz/argo_app_api:${{ github.head_ref }}.${{ github.sha }}
        docker push barminz/argo_app_client:${{ github.head_ref }}.${{ github.sha }}

    - name: Tag latest
      run: |
        docker tag barminz/argo_app_api:${{ github.head_ref }}.${{ github.sha }} barminz/argo_app_api:latest
        docker tag barminz/argo_app_client:${{ github.head_ref }}.${{ github.sha }} barminz/argo_app_client:latest

    - name: Push latest
      run: |
        docker push barminz/argo_app_api:latest
        docker push barminz/argo_app_client:latest
