name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for API server
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner | lower }}/argo_app_api:latest
            ghcr.io/${{ github.repository_owner | lower }}/argo_app_api:${{ github.sha }}

      - name: Build and push Docker image for Client server
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner | lower }}/argo_app_client:latest
            ghcr.io/${{ github.repository_owner | lower }}/argo_app_client:${{ github.sha }}
