name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  git_hash: $(git rev-parse --short "$GITHUB_SHA")
  git_branch: ${GITHUB_REF#refs/heads/}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: |
        docker build ./api -t ghcr.io/${{ github.repository_owner }}/argo_app_api:${{ env.git_branch }}.${{ env.git_hash }}
        docker build ./client -t ghcr.io/${{ github.repository_owner }}/argo_app_client:${{ env.git_branch }}.${{ env.git_hash }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push current version
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/argo_app_api:${{ env.git_branch }}.${{ env.git_hash }}
        docker push ghcr.io/${{ github.repository_owner }}/argo_app_client:${{ env.git_branch }}.${{ env.git_hash }}

    - name: Tag latest
      run: |
        docker tag ghcr.io/${{ github.repository_owner }}/argo_app_api:${{ env.git_branch }}.${{ env.git_hash }} ghcr.io/${{ github.repository_owner }}/argo_app_api:latest
        docker tag ghcr.io/${{ github.repository_owner }}/argo_app_client:${{ env.git_branch }}.${{ env.git_hash }} ghcr.io/${{ github.repository_owner }}/argo_app_client:latest

    - name: Push latest
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/argo_app_api:latest
        docker push ghcr.io/${{ github.repository_owner }}/argo_app_client:latest
